import { db } from "@workspace/db";
import {
  heritageItemsTable,
  artisansTable,
  artisanServicesTable,
  quizQuestionsTable,
  productsTable,
  activitiesTable,
} from "@workspace/db";
import { sql } from "drizzle-orm";

async function seed() {
  console.log("🌱 开始填充孝感非遗数据库...");

  await db.execute(sql`TRUNCATE TABLE activities RESTART IDENTITY CASCADE`);
  await db.execute(sql`TRUNCATE TABLE artisan_services RESTART IDENTITY CASCADE`);
  await db.execute(sql`TRUNCATE TABLE quiz_questions RESTART IDENTITY CASCADE`);
  await db.execute(sql`TRUNCATE TABLE products RESTART IDENTITY CASCADE`);
  await db.execute(sql`TRUNCATE TABLE artisans RESTART IDENTITY CASCADE`);
  await db.execute(sql`TRUNCATE TABLE heritage_items RESTART IDENTITY CASCADE`);

  const heritageItems = await db.insert(heritageItemsTable).values([
    {
      name: "董永传说",
      nameEn: "Legend of Dong Yong",
      level: "national",
      category: "民间文学",
      description: "董永传说是孝感最具代表性的非遗项目，讲述了东汉孝子董永卖身葬父，感动天地，与七仙女结缘的动人故事。这一传说深刻体现了中华孝文化的精髓，是孝感"孝文化名城"的核心IP。董永故里位于孝感市孝南区，保存有完好的董永公园、孝子祠、千年槐荫树等历史遗址。楚剧《百日缘》、黄梅戏《天仙配》均源于此传说，影响深远。",
      shortDesc: "孝感孝文化核心IP，天仙配传说发源地，孝子董永的动人故事",
      imageUrl: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800",
      origin: "孝感市孝南区",
      yearListed: 2006,
      artisanCount: 3,
      tags: ["孝文化", "民间传说", "国家级", "世界影响"],
      featured: true,
      xiaoTheme: true,
    },
    {
      name: "孝感雕花剪纸",
      nameEn: "Xiaogan Paper Cutting",
      level: "national",
      category: "传统技艺",
      description: "孝感雕花剪纸是中国剪纸艺术中的精品，以精细镂空、多层叠加著称，代表作《槐荫记》《百孝图》享誉国内外。其工艺分为画稿、剪刻、装裱三大步骤，讲究"以刀代笔"，每一件作品都是艺术精品。孝感雕花剪纸于2006年被列入第一批国家级非物质文化遗产名录，2009年随"中国剪纸"入选联合国教科文组织人类非物质文化遗产代表作名录，成为世界级非遗。",
      shortDesc: "精细镂空工艺，世界非遗，《百孝图》等孝主题作品闻名遐迩",
      imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800",
      origin: "孝感全市",
      yearListed: 2006,
      artisanCount: 8,
      tags: ["剪纸", "世界非遗", "国家级", "孝文化"],
      featured: true,
      xiaoTheme: true,
    },
    {
      name: "汉川善书",
      nameEn: "Hanchuan Shanshu",
      level: "national",
      category: "曲艺",
      description: "汉川善书是流行于孝感汉川地区的一种独特曲艺形式，演员通过说唱结合的方式，讲述劝善故事、弘扬传统美德，具有浓郁的地方特色。善书演出不用乐器伴奏，仅凭一人或数人的演唱，以其独特的演唱技艺和道德教化功能，深受当地群众喜爱。2011年被列入第三批国家级非物质文化遗产名录。",
      shortDesc: "汉川地区独特曲艺，以善书为名，劝善励德，国家级非遗",
      imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800",
      origin: "孝感市汉川市",
      yearListed: 2011,
      artisanCount: 5,
      tags: ["曲艺", "国家级", "劝善文化"],
      featured: true,
      xiaoTheme: false,
    },
    {
      name: "云梦皮影戏",
      nameEn: "Yunmeng Shadow Puppetry",
      level: "national",
      category: "传统戏剧",
      description: "云梦皮影戏历史悠久，以精湛的雕刻工艺和生动的表演技艺著称。皮影造型精美，线条流畅，栩栩如生。代表传承人秦礼刚的经典剧目《董永传说》《武松打虎》享誉全国。云梦皮影戏的皮影制作采用手工雕刻，表演时以灯光投影，配合锣鼓声腔，呈现出独特的艺术魅力，是中国皮影戏的重要流派之一。",
      shortDesc: "国家级非遗，精美皮影造型，秦礼刚大师经典剧目享誉全国",
      imageUrl: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800",
      origin: "孝感市云梦县",
      yearListed: 2008,
      artisanCount: 4,
      tags: ["皮影戏", "国家级", "传统戏剧"],
      featured: true,
      xiaoTheme: false,
    },
    {
      name: "三节龙·跳鼓",
      nameEn: "Three-Section Dragon and Drum Dance",
      level: "national",
      category: "传统舞蹈",
      description: "三节龙·跳鼓是孝感地区独具特色的民间舞蹈形式，将舞龙与跳鼓相结合，动感十足，场面壮观。表演时，舞龙者身着彩服，手持三节短龙，配合激昂的鼓声，翻腾跳跃，展现出勃勃生机。每逢节日庆典，三节龙·跳鼓必不可少，是孝感民间节庆文化的重要组成部分。",
      shortDesc: "舞龙与跳鼓结合，节日必演，孝感民间节庆文化精华",
      imageUrl: "https://images.unsplash.com/photo-1493770348161-369560ae357d?w=800",
      origin: "孝感市",
      yearListed: 2014,
      artisanCount: 2,
      tags: ["舞蹈", "国家级", "民间庆典"],
      featured: true,
      xiaoTheme: false,
    },
    {
      name: "楚剧",
      nameEn: "Chu Opera",
      level: "national",
      category: "传统戏剧",
      description: "楚剧是湖北地方戏曲的代表剧种，起源于孝感一带，以其浓郁的楚文化特色和接地气的表演风格深受湖北人民喜爱。楚剧唱腔丰富，表演细腻，剧目丰富，涵盖历史故事、民间传说等多类题材。《百日缘》《葛麻》等经典剧目至今仍广为流传。楚剧是理解孝感及湖北地域文化的重要窗口。",
      shortDesc: "湖北地方戏曲代表，楚文化精髓，《百日缘》等经典剧目流传至今",
      imageUrl: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800",
      origin: "孝感市",
      yearListed: 2006,
      artisanCount: 6,
      tags: ["戏剧", "国家级", "楚文化"],
      featured: true,
      xiaoTheme: true,
    },
    {
      name: "孝感麻糖",
      nameEn: "Xiaogan Sesame Candy",
      level: "provincial",
      category: "传统美食",
      description: "孝感麻糖是孝感最著名的传统美食，已有千年历史。以优质芝麻和麦芽糖为主要原料，经过选料、炒制、熬糖、拉丝、成型等十余道工序精心制作而成。孝感麻糖色泽金黄，香甜酥脆，入口化渣，是孝感的地方特产名片，也是走亲访友的佳礼。每年产值超亿元，带动数千农民就业。",
      shortDesc: "千年传统美食，芝麻与麦芽糖精制，孝感特产名片",
      imageUrl: "https://images.unsplash.com/photo-1555126634-323283e090fa?w=800",
      origin: "孝感市区",
      yearListed: 2009,
      artisanCount: 12,
      tags: ["美食", "省级", "传统工艺"],
      featured: true,
      xiaoTheme: false,
    },
    {
      name: "孝感米酒",
      nameEn: "Xiaogan Rice Wine",
      level: "provincial",
      category: "传统美食",
      description: "孝感米酒以优质糯米为原料，采用传统酿造工艺，酒体醇厚，甜而不腻，深受孝感市民喜爱。孝感米酒酿造历史悠久，是当地节日、待客的传统饮品。其制作工艺包括泡米、蒸饭、拌曲、发酵、成品等步骤，全程手工操作，保留了原汁原味的传统风味。",
      shortDesc: "糯米酿造，传统工艺，孝感节日待客必备佳品",
      imageUrl: "https://img.alicdn.com/i4/815924539/O1CN01GUdwG41jOuRifpHdD_!!815924539.jpg",
      origin: "孝感市",
      yearListed: 2011,
      artisanCount: 8,
      tags: ["美食", "省级", "酿造"],
      featured: false,
      xiaoTheme: false,
    },
    {
      name: "云梦鱼面",
      nameEn: "Yunmeng Fish Noodles",
      level: "provincial",
      category: "传统美食",
      description: "云梦鱼面是孝感云梦县的传统特色美食，以鲜鱼肉与面粉为原料，采用独特工艺制作而成。鱼面色泽洁白，口感细腻，营养丰富，是云梦人民世代相传的饮食瑰宝。制作鱼面需要将鲜鱼肉去骨去刺，与面粉混合揉制，经擀制、晾晒等工序而成。",
      shortDesc: "鱼肉与面粉合制，云梦特产，营养细腻口感独特",
      imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800",
      origin: "孝感市云梦县",
      yearListed: 2013,
      artisanCount: 5,
      tags: ["美食", "省级", "特产"],
      featured: false,
      xiaoTheme: false,
    },
    {
      name: "应城膏雕",
      nameEn: "Yingcheng Gypsum Carving",
      level: "provincial",
      category: "传统技艺",
      description: "应城膏雕是以应城出产的天然石膏为原料，经过雕刻、打磨、着色等工序制作而成的艺术品。应城是全国重要的石膏产地，膏雕工艺有百年以上历史。膏雕作品造型多样，题材丰富，从人物、动物到山水、花卉，无不惟妙惟肖。",
      shortDesc: "应城天然石膏精雕，百年工艺，造型栩栩如生",
      imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800",
      origin: "孝感市应城市",
      yearListed: 2010,
      artisanCount: 6,
      tags: ["雕刻", "省级", "传统工艺"],
      featured: false,
      xiaoTheme: false,
    },
    {
      name: "杨林乌壶",
      nameEn: "Yanglin Black Pottery",
      level: "provincial",
      category: "传统技艺",
      description: "杨林乌壶是孝感大悟县杨林镇的传统陶瓷工艺品，以当地特有的黑色陶土为原料，经手工成型、高温烧制而成。乌壶色泽深沉，造型古朴，具有极高的艺术价值和实用价值。杨林乌壶的制作工艺独特，烧制温度和时间的把握需要丰富经验。",
      shortDesc: "大悟杨林传统黑陶，古朴造型，传统制陶工艺精髓",
      imageUrl: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800",
      origin: "孝感市大悟县杨林镇",
      yearListed: 2012,
      artisanCount: 3,
      tags: ["陶瓷", "省级", "传统工艺"],
      featured: false,
      xiaoTheme: false,
    },
    {
      name: "肖港抬故事",
      nameEn: "Xiaogang Carrying Parade",
      level: "provincial",
      category: "民俗",
      description: "肖港抬故事是孝感传统民俗活动，每逢节庆，当地居民将历史故事、神话传说以抬阁形式展演，由儿童扮演故事人物，被大人抬着游街，场面宏大壮观，充满浓郁的民间节日气息。",
      shortDesc: "传统节庆民俗，儿童扮演故事人物抬阁游街，场面壮观热闹",
      imageUrl: "https://images.unsplash.com/photo-1534126511673-b6899657816a?w=800",
      origin: "孝感市孝昌县肖港镇",
      yearListed: 2015,
      artisanCount: 2,
      tags: ["民俗", "省级", "节庆活动"],
      featured: false,
      xiaoTheme: false,
    },
  ]).returning();

  console.log(`✅ 插入 ${heritageItems.length} 条非遗项目数据`);

  const artisans = await db.insert(artisansTable).values([
    {
      name: "管丽芳",
      level: "国家级传承人",
      heritageItem: "孝感雕花剪纸",
      heritageItemId: 2,
      bio: "管丽芳是孝感雕花剪纸国家级代表性传承人，从事剪纸艺术40余年，作品《槐荫记》《百孝图》享誉国内外，曾多次在国际非遗展中展出，获奖无数。她将雕花剪纸的精髓与孝文化深度融合，形成了独特的艺术风格。管老师长期在孝感市开展非遗进校园活动，致力于培养新一代剪纸传承人。",
      avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400",
      yearsOfPractice: 42,
      awards: ["湖北省工艺美术大师", "中国民间文艺最高奖山花奖", "联合国教科文组织非遗传承人认证"],
    },
    {
      name: "秦礼刚",
      level: "国家级传承人",
      heritageItem: "云梦皮影戏",
      heritageItemId: 4,
      bio: "秦礼刚是云梦皮影戏国家级代表性传承人，出生于皮影世家，幼年随父学艺，精通皮影制作与表演。经典剧目《董永传说》《武松打虎》影响广泛，曾应邀赴欧洲多国演出，将云梦皮影带向世界。秦老师每年在云梦举办皮影培训班，免费教授社区居民皮影制作技艺。",
      avatarUrl: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=400",
      yearsOfPractice: 38,
      awards: ["湖北省民间艺术大师", "国家级非遗代表性传承人称号", "全国文化遗产年度人物"],
    },
    {
      name: "徐忠德",
      level: "国家级传承人",
      heritageItem: "汉川善书",
      heritageItemId: 3,
      bio: "徐忠德是汉川善书国家级代表性传承人，从事善书演唱50余年，嗓音洪亮，表演生动，是汉川善书最具代表性的演唱艺术家。他整理、抢救了大量濒临失传的善书曲目，并创作了多部现代善书作品，将传统善书与现代主题结合，焕发新的生命力。",
      avatarUrl: "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=400",
      yearsOfPractice: 52,
      awards: ["汉川市文化名人", "湖北省曲艺家协会会员", "全国优秀民间艺人"],
    },
    {
      name: "余达雄",
      level: "省级传承人",
      heritageItem: "孝感麻糖",
      heritageItemId: 7,
      bio: "余达雄家族制作孝感麻糖已传承四代，他将传统工艺与现代食品安全标准相结合，在保持传统风味的同时，开发出多种口味的麻糖新品，深受年轻消费者喜爱。余师傅积极参与非遗进社区活动，让更多人了解麻糖的制作工艺和文化内涵。",
      avatarUrl: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400",
      yearsOfPractice: 30,
      awards: ["孝感市非遗传承人", "湖北省食品工匠", "孝感市劳动模范"],
    },
    {
      name: "李志明",
      level: "省级传承人",
      heritageItem: "应城膏雕",
      heritageItemId: 10,
      bio: "李志明是应城膏雕省级代表性传承人，从事膏雕艺术30余年，作品题材涵盖人物、山水、动物等，造型精美，工艺精湛。他创立了应城膏雕工作室，定期举办膏雕体验活动，吸引大量游客参与体验，推动了应城膏雕的活态传承。",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
      yearsOfPractice: 32,
      awards: ["应城市工艺美术大师", "湖北省优秀非遗传承人", "孝感市文化贡献奖"],
    },
    {
      name: "张玉兰",
      level: "省级传承人",
      heritageItem: "孝感米酒",
      heritageItemId: 8,
      bio: "张玉兰是孝感米酒省级代表性传承人，传承祖传酿酒技艺，坚持使用本地优质糯米和传统酒曲，酿造出醇香甘甜的孝感米酒。她创立了孝感米酒品牌，在保护传统工艺的同时，积极开拓线上销售渠道，让更多人品尝到正宗的孝感米酒。",
      avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400",
      yearsOfPractice: 25,
      awards: ["孝感市优秀传承人", "湖北省食品行业技术能手"],
    },
  ]).returning();

  console.log(`✅ 插入 ${artisans.length} 名传承人数据`);

  await db.insert(artisanServicesTable).values([
    { artisanId: artisans[0].id, type: "workshop", title: "雕花剪纸体验课", description: "跟随管丽芳大师学习基础剪纸技法，亲手制作一件专属剪纸作品", price: "288", duration: "3小时", maxParticipants: 10 },
    { artisanId: artisans[0].id, type: "custom", title: "定制剪纸作品", description: "根据您的需求定制个性化剪纸，适合收藏、送礼", price: "580", duration: "7-14天交付" },
    { artisanId: artisans[0].id, type: "course", title: "线上剪纸入门课", description: "12节视频课程，系统学习雕花剪纸技艺，含配套材料包", price: "199" },
    { artisanId: artisans[1].id, type: "workshop", title: "皮影制作体验", description: "学习皮影造型雕刻，带走一件自己制作的皮影", price: "198", duration: "2.5小时", maxParticipants: 8 },
    { artisanId: artisans[1].id, type: "workshop", title: "皮影表演体验课", description: "学习皮影戏操控技法，上演一段经典皮影故事", price: "168", duration: "2小时", maxParticipants: 12 },
    { artisanId: artisans[2].id, type: "workshop", title: "善书演唱体验", description: "跟随徐忠德老师学习善书基本唱法，感受曲艺魅力", price: "128", duration: "2小时", maxParticipants: 15 },
    { artisanId: artisans[3].id, type: "workshop", title: "麻糖制作体验", description: "亲手体验孝感麻糖制作全过程，带走自制麻糖一盒", price: "168", duration: "3小时", maxParticipants: 20 },
    { artisanId: artisans[4].id, type: "workshop", title: "膏雕创作工坊", description: "学习膏雕基础技法，在大师指导下完成一件膏雕作品", price: "258", duration: "4小时", maxParticipants: 8 },
  ]);

  console.log("✅ 插入传承人服务数据");

  await db.insert(quizQuestionsTable).values([
    {
      question: "孝感雕花剪纸于哪年被列入联合国教科文组织人类非物质文化遗产代表作名录？",
      options: ["2006年", "2009年", "2012年", "2015年"],
      correctAnswer: 1,
      explanation: "2009年，孝感雕花剪纸随"中国剪纸"整体项目入选联合国教科文组织人类非物质文化遗产代表作名录，成为世界级非遗。",
      difficulty: "beginner",
      category: "剪纸文化",
      points: 10,
    },
    {
      question: "董永传说中，千年古槐荫树位于孝感市的哪个公园？",
      options: ["孝感公园", "孝子祠公园", "董永公园", "槐荫公园"],
      correctAnswer: 2,
      explanation: "传说中的千年槐荫树位于孝感市孝南区的董永公园，是董永与七仙女相遇的传说地点，现已成为孝感重要的文化地标。",
      difficulty: "beginner",
      category: "孝文化",
      points: 10,
    },
    {
      question: "云梦皮影戏国家级代表性传承人是谁？",
      options: ["管丽芳", "秦礼刚", "徐忠德", "余达雄"],
      correctAnswer: 1,
      explanation: "秦礼刚是云梦皮影戏国家级代表性传承人，经典剧目《董永传说》《武松打虎》享誉全国，曾应邀赴欧洲多国演出。",
      difficulty: "beginner",
      category: "传承人",
      points: 10,
    },
    {
      question: "孝感麻糖的主要原料是哪两种？",
      options: ["花生与蔗糖", "芝麻与麦芽糖", "核桃与冰糖", "杏仁与蜂蜜"],
      correctAnswer: 1,
      explanation: "孝感麻糖以优质芝麻和麦芽糖为主要原料，经过十余道工序精心制作，色泽金黄，香甜酥脆，是孝感最著名的传统美食。",
      difficulty: "beginner",
      category: "传统美食",
      points: 10,
    },
    {
      question: "汉川善书属于哪种艺术形式？",
      options: ["传统戏剧", "民间舞蹈", "曲艺", "民间文学"],
      correctAnswer: 2,
      explanation: "汉川善书是一种独特的曲艺形式，演员通过说唱结合的方式讲述劝善故事，不用乐器伴奏，以演唱技艺和道德教化功能著称。",
      difficulty: "beginner",
      category: "艺术形式",
      points: 10,
    },
    {
      question: "孝感雕花剪纸代表性作品《槐荫记》的创作灵感来源于哪个传说？",
      options: ["白蛇传", "牛郎织女", "董永传说", "孟宗哭竹"],
      correctAnswer: 2,
      explanation: "《槐荫记》以董永传说为创作灵感，是孝感雕花剪纸国家级传承人管丽芳的代表作品，充分体现了孝文化与剪纸艺术的深度融合。",
      difficulty: "intermediate",
      category: "剪纸文化",
      points: 20,
    },
    {
      question: "孝感被誉为中华什么名城？",
      options: ["孝文化名城", "非遗之城", "戏剧名城", "工艺美术之城"],
      correctAnswer: 0,
      explanation: "孝感因盛产孝子而得名，是中国孝文化的发源地之一，被誉为"中华孝文化名城"，拥有董永传说、孝感雕花剪纸等众多与孝文化密切相关的非遗项目。",
      difficulty: "beginner",
      category: "孝文化",
      points: 10,
    },
    {
      question: "以下哪项不是孝感的国家级非物质文化遗产？",
      options: ["云梦皮影戏", "汉川善书", "应城膏雕", "孝感雕花剪纸"],
      correctAnswer: 2,
      explanation: "应城膏雕是孝感的省级非物质文化遗产，而非国家级。孝感现有6项国家级非遗：董永传说、孝感雕花剪纸、汉川善书、云梦皮影戏、三节龙·跳鼓、楚剧。",
      difficulty: "intermediate",
      category: "非遗知识",
      points: 20,
    },
    {
      question: "楚剧起源于何地？",
      options: ["武汉", "孝感", "荆州", "宜昌"],
      correctAnswer: 1,
      explanation: "楚剧起源于孝感一带，是湖北地方戏曲的代表剧种，以浓郁的楚文化特色和接地气的表演风格著称，《百日缘》等经典剧目影响深远。",
      difficulty: "intermediate",
      category: "传统戏剧",
      points: 20,
    },
    {
      question: "三节龙·跳鼓是将哪两种民间艺术结合在一起的表演形式？",
      options: ["舞狮与击鼓", "舞龙与跳鼓", "高跷与龙舟", "秧歌与舞龙"],
      correctAnswer: 1,
      explanation: "三节龙·跳鼓是孝感地区独具特色的民间舞蹈，将舞龙（三节短龙）与跳鼓相结合，表演者身着彩服，配合激昂鼓声翻腾跳跃，场面壮观。",
      difficulty: "intermediate",
      category: "传统舞蹈",
      points: 20,
    },
    {
      question: "应城膏雕的主要原料是哪种天然矿石？",
      options: ["大理石", "汉白玉", "天然石膏", "砚石"],
      correctAnswer: 2,
      explanation: "应城膏雕以应城出产的天然石膏为原料。应城是全国重要的石膏产地，以石膏为材料的雕刻工艺已有百年以上历史，作品造型精美，题材丰富。",
      difficulty: "expert",
      category: "传统技艺",
      points: 30,
    },
    {
      question: "孝感共有多少项市级非物质文化遗产？",
      options: ["30项", "45项", "60项", "81项"],
      correctAnswer: 1,
      explanation: "截至目前，孝感拥有6项国家级非遗、30项省级非遗、45项市级非遗，形成了完整的非遗保护体系，是湖北省非遗资源最丰富的地级市之一。",
      difficulty: "expert",
      category: "非遗知识",
      points: 30,
    },
    {
      question: "黄香（24孝故事中的孝子）是哪里人？",
      options: ["孝感市应城", "孝感市云梦", "孝感市安陆", "孝感市孝南区"],
      correctAnswer: 1,
      explanation: "黄香是东汉时期的著名孝子，出生于孝感市云梦县，以"扇枕温衾"（夏天扇枕席、冬天暖被褥）孝敬父母的故事流传千古，是《二十四孝》中的重要故事。",
      difficulty: "expert",
      category: "孝文化",
      points: 30,
    },
    {
      question: "云梦鱼面的主要原料是什么？",
      options: ["鲤鱼与米粉", "鲜鱼肉与面粉", "虾仁与淀粉", "鱼胶与糯米"],
      correctAnswer: 1,
      explanation: "云梦鱼面以鲜鱼肉与面粉为原料，将鲜鱼肉去骨去刺后与面粉混合揉制，经擀制、晾晒等工序制成，是云梦县的传统特色美食。",
      difficulty: "intermediate",
      category: "传统美食",
      points: 20,
    },
    {
      question: "以下哪位是孝感雕花剪纸国家级代表性传承人？",
      options: ["秦礼刚", "徐忠德", "管丽芳", "余达雄"],
      correctAnswer: 2,
      explanation: "管丽芳是孝感雕花剪纸国家级代表性传承人，从事剪纸艺术40余年，作品《槐荫记》《百孝图》享誉国内外，是孝感剪纸艺术的杰出代表。",
      difficulty: "beginner",
      category: "传承人",
      points: 10,
    },
  ]);

  console.log("✅ 插入答题题库数据");

  await db.insert(productsTable).values([
    {
      name: "百孝图雕花剪纸",
      category: "artisan_original",
      description: "管丽芳大师亲手制作，以百个"孝"字为创意，融合孝文化主题花纹，精心雕刻而成，附精美木质镜框，适合收藏或馈赠",
      price: "280",
      imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600",
      artisanName: "管丽芳",
      heritageItem: "孝感雕花剪纸",
      stock: 15,
      rating: "4.9",
      reviewCount: 47,
    },
    {
      name: "皮影钥匙扣（董永+七仙女套装）",
      category: "collab",
      description: "以云梦皮影戏的造型艺术为灵感，将董永与七仙女造型微缩为精美钥匙扣，传统皮影工艺与现代实用功能完美结合",
      price: "45",
      imageUrl: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=600",
      artisanName: "秦礼刚工作室",
      heritageItem: "云梦皮影戏",
      stock: 200,
      rating: "4.8",
      reviewCount: 128,
    },
    {
      name: "孝感麻糖礼盒（传承人版）",
      category: "artisan_original",
      description: "余达雄手作孝感麻糖精选礼盒，选用当年新产芝麻与传统麦芽糖，按祖传工艺制作，礼盒印有非遗传承标志，是馈赠佳礼",
      price: "168",
      imageUrl: "https://images.unsplash.com/photo-1555126634-323283e090fa?w=600",
      artisanName: "余达雄",
      heritageItem: "孝感麻糖",
      stock: 80,
      rating: "5.0",
      reviewCount: 256,
    },
    {
      name: "雕花剪纸书签套装（6枚）",
      category: "collab",
      description: "精选孝感雕花剪纸经典图案，制作成精美书签套装，图案涵盖槐荫树、董永故事等孝文化主题，竹浆书签纸，防水耐用",
      price: "35",
      imageUrl: "https://images.unsplash.com/photo-1553481187-be93c21490a9?w=600",
      artisanName: "孝感非遗文创",
      heritageItem: "孝感雕花剪纸",
      stock: 500,
      rating: "4.7",
      reviewCount: 89,
    },
    {
      name: "皮影装饰挂件（武松打虎）",
      category: "artisan_original",
      description: "云梦皮影戏国家级传承人秦礼刚亲手制作，取材于经典剧目《武松打虎》，皮影造型精美，可作为家居装饰，附有传承人亲笔签名证书",
      price: "320",
      imageUrl: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=600",
      artisanName: "秦礼刚",
      heritageItem: "云梦皮影戏",
      stock: 5,
      rating: "5.0",
      reviewCount: 18,
    },
    {
      name: "雕花剪纸文化台历（2026）",
      category: "collab",
      description: "12幅孝感雕花剪纸艺术作品，每月一幅，涵盖董永传说、雕花剪纸经典题材，配有非遗文化小知识，适合办公桌摆放",
      price: "98",
      imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600",
      artisanName: "孝感非遗文创",
      heritageItem: "孝感雕花剪纸",
      stock: 120,
      rating: "4.6",
      reviewCount: 34,
    },
    {
      name: "孝文化主题马口窑陶瓷茶杯",
      category: "student",
      description: "湖北工程学院艺术设计专业学生设计，以孝感马口窑传统工艺制作，杯身印有孝文化图案，既是实用茶杯，也是独特的非遗文创作品",
      price: "128",
      imageUrl: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600",
      artisanName: "湖北工程学院·非遗文创社",
      heritageItem: "马口窑陶瓷",
      stock: 60,
      rating: "4.5",
      reviewCount: 22,
    },
    {
      name: "应城膏雕小摆件（莲花鱼）",
      category: "artisan_original",
      description: "李志明大师亲手制作的应城膏雕摆件，取材于吉祥题材"莲年有余"（莲花与鱼），寓意美好，雕工精细，附证书及包装",
      price: "188",
      imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600",
      artisanName: "李志明",
      heritageItem: "应城膏雕",
      stock: 30,
      rating: "4.9",
      reviewCount: 15,
    },
    {
      name: "孝感米酒体验礼盒",
      category: "artisan_original",
      description: "张玉兰传承人出品，包含500ml传统孝感米酒一瓶及酿造工艺图文手册，让您在品味的同时了解千年酿酒文化",
      price: "88",
      imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
      artisanName: "张玉兰",
      heritageItem: "孝感米酒",
      stock: 100,
      rating: "4.8",
      reviewCount: 67,
    },
    {
      name: "非遗剪纸风格帆布袋",
      category: "student",
      description: "湖北职业技术学院学生设计，以雕花剪纸镂空图案为主题，环保帆布材质，侧面印有孝感非遗平台LOGO，实用又文艺",
      price: "58",
      imageUrl: "https://images.unsplash.com/photo-1593642532842-98d0fd5ebc1a?w=600",
      artisanName: "湖北职业技术学院·文创工作室",
      heritageItem: "孝感雕花剪纸",
      stock: 200,
      rating: "4.4",
      reviewCount: 45,
    },
  ]);

  console.log("✅ 插入文创产品数据");

  await db.insert(activitiesTable).values([
    {
      title: "2026年孝感非遗年货节",
      description: "孝感市文旅局主办，汇聚全市30余家非遗传承人和文创品牌，现场展示与销售麻糖、剪纸、皮影等非遗产品，同期举办非遗表演、传承人见面会、体验工坊等精彩活动。",
      type: "展览销售",
      location: "孝感市文化中心广场",
      startDate: "2026-01-20",
      endDate: "2026-02-05",
      imageUrl: "https://images.unsplash.com/photo-1534126511673-b6899657816a?w=800",
      status: "upcoming",
      maxParticipants: 5000,
      currentParticipants: 1280,
    },
    {
      title: "孝感雕花剪纸体验营（寒假专场）",
      description: "由管丽芳大师亲自指导，面向8-18岁青少年开展为期三天的雕花剪纸沉浸式体验营，从基础到进阶，让孩子们在动手中感受非遗魅力，带走自己的作品。",
      type: "体验活动",
      location: "孝感市非遗传习所",
      startDate: "2026-01-15",
      endDate: "2026-01-17",
      imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800",
      status: "upcoming",
      maxParticipants: 30,
      currentParticipants: 22,
    },
    {
      title: "云梦皮影戏经典剧目专场演出",
      description: "国家级传承人秦礼刚携弟子献演经典剧目《董永传说》全本，约60分钟，演出结束后开放皮影制作体验，观众可与传承人面对面交流，了解皮影戏的台前幕后。",
      type: "演出",
      location: "孝感市云梦县文化馆剧场",
      startDate: "2026-01-25",
      endDate: "2026-01-25",
      imageUrl: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800",
      status: "upcoming",
      maxParticipants: 200,
      currentParticipants: 156,
    },
    {
      title: "非遗进校园·孝感雕花剪纸走进湖北工程学院",
      description: "管丽芳大师带领团队走进湖北工程学院，为艺术设计专业学生开展专题讲座和现场演示，探讨传统非遗与现代设计的融合创新，并与学生共同创作非遗文创作品。",
      type: "进校园",
      location: "湖北工程学院",
      startDate: "2026-03-15",
      endDate: "2026-03-15",
      imageUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800",
      status: "upcoming",
      maxParticipants: 150,
      currentParticipants: 0,
    },
    {
      title: "2025孝文化旅游节非遗展演",
      description: "2025孝文化旅游节期间举办的非遗专题展演，包括楚剧选段、善书表演、三节龙跳鼓、皮影戏表演等多个精彩节目，共吸引近万名市民和游客观看。",
      type: "展演",
      location: "孝感市董永公园",
      startDate: "2025-09-28",
      endDate: "2025-10-05",
      imageUrl: "https://images.unsplash.com/photo-1493770348161-369560ae357d?w=800",
      status: "past",
      maxParticipants: 10000,
      currentParticipants: 9800,
    },
    {
      title: "孝感非遗数字化平台启动仪式",
      description: "孝感非遗文化数字化平台正式上线启动仪式，孝感市文旅局领导、各级非遗传承人代表、本地高校代表等出席，标志着孝感非遗正式进入数字化传播新时代。",
      type: "发布会",
      location: "孝感市群众艺术馆",
      startDate: "2025-12-20",
      endDate: "2025-12-20",
      imageUrl: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800",
      status: "past",
      maxParticipants: 300,
      currentParticipants: 285,
    },
  ]);

  console.log("✅ 插入活动数据");
  console.log("🎉 孝感非遗数据库填充完成！");
}

seed().catch(console.error);
